# Generated by Django 4.0.6 on 2024-02-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_alter_produto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('cliente', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_total_recebido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valor_total_pago', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valor_de_compra_dos_produtos', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valor_de_venda_dos_produtos', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('c', 'Compra'), ('v', 'Venda'), ('t', 'Troca'), ('f', 'Serviço Feito/Realizado'), ('r', 'Serviço Recebido')], max_length=1)),
                ('metodo_pagamento', models.CharField(choices=[('d', 'Dinheiro'), ('p', 'PIX'), ('d', 'Débito'), ('c', 'Crédito')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='produto_transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('e', 'Entrada'), ('s', 'Saída')], max_length=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.transacao')),
            ],
        ),
    ]
