# Generated by Django 4.0.6 on 2024-03-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto_transacao',
            old_name='valor_compra',
            new_name='valor_custo',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='valor_de_compra_dos_produtos',
            new_name='valor_de_custo_dos_produtos',
        ),
    ]
