# Generated by Django 4.0.6 on 2024-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_alter_transacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='taxas',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
