# Generated by Django 4.0.6 on 2024-04-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimentacoes', '0004_transacao_taxas'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='cliente_endereco',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
