# Generated by Django 4.0.6 on 2024-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_transacao_cliente_endereco_transacao_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='cliente',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
