# Generated by Django 4.0.6 on 2024-04-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0007_alter_transacao_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='cliente_endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('d', 'Dinheiro'), ('p', 'PIX'), ('d', 'Débito'), ('c', 'Crédito')], max_length=1, null=True),
        ),
    ]
