# Generated by Django 4.0.6 on 2024-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='permissoes',
            field=models.ManyToManyField(to='autenticacao.permissao'),
        ),
    ]
