# Generated by Django 4.0.6 on 2024-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_cargo_permissoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='autenticacao.permissao'),
        ),
    ]
