# Generated by Django 4.0.6 on 2024-04-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_produto_aliquota_icms'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nota_fiscal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=255)),
                ('cliente_endereco', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('v', 'Venda'), ('p', 'Serviço Prestado')], max_length=1)),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icms_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='nota_fiscal_produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_icms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas_fiscais.nota_fiscal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
