# Generated by Django 4.0.6 on 2024-03-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_foto'),
        ('produtos', '0002_alter_produto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='produto_estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('quantidade', models.IntegerField()),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localizacao', models.CharField(max_length=255, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
