# Generated by Django 4.0.6 on 2024-03-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto'),
        ('produtos_estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produto_estoque_transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('e', 'Entrada'), ('s', 'Saída')], max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos_estoque.produto_estoque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
