# Generated by Django 4.0.6 on 2024-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('foto', models.FileField(null=True, upload_to='media/produtos/')),
                ('codigo_referencia', models.CharField(max_length=63)),
                ('valor_custo_padrao', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valor_venda_padrao', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
