# Generated by Django 4.0.6 on 2024-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
